// GET all courses
export const GET_COURSES = 'GET_COURSES';
export const GET_COURSE = 'GET_COURSE';

// OPTIONS
export const GET_THRESHOLD_CONCEPTS = 'GET_THRESHOLD_CONCEPTS';
export const GET_INFORMATION_LITERACY_OBJECTIVES =
  'GET_INFORMATION_LITERACY_OBJECTIVES';
export const GET_MODULES = 'GET_MODULES';
export const GET_LIBRARIANS = 'GET_LIBRARIANS';
export const ADD_CUSTOM_MODULES = 'ADD_CUSTOM_MODULE';

// LESSONS
export const BUILD_LESSON = 'BUILD_LESSON';
export const GET_LESSONS = 'GET_LESSONS';
export const GET_LESSON = 'GET_LESSON';
